### ISSUE TITLE
默认监听哪个端口？

### ISSUE THREAD

**Issue by briteming** [wangyuntao/socks5-rs#3]
在vps上，
./socks5-rs
Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }

谢谢回复

**Comment by bushkarl** [comment]
自能自己撸代码了

**Comment by wangyuntao** [comment]
抱歉哈，一段时间没关注这个项目了，没看到这个issue。

默认是9999端口，可以用./socks5-rs 8888的方式换成8888端口

**Comment by wangyuntao** [comment]
> 在vps上，
> ./socks5-rs
> Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
> 
> 谢谢回复

应该是端口被占用了，你看下是否有其他应用在使用9999端口
